[2025-07-18T14:42:46.626+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_pipeline.send_to_kafka manual__2025-07-18T14:42:45.033995+00:00 [queued]>
[2025-07-18T14:42:46.630+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_pipeline.send_to_kafka manual__2025-07-18T14:42:45.033995+00:00 [queued]>
[2025-07-18T14:42:46.630+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-18T14:42:46.635+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): send_to_kafka> on 2025-07-18 14:42:45.033995+00:00
[2025-07-18T14:42:46.638+0000] {standard_task_runner.py:57} INFO - Started process 200 to run task
[2025-07-18T14:42:46.640+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'restaurant_pipeline', 'send_to_kafka', 'manual__2025-07-18T14:42:45.033995+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_pipeline.py', '--cfg-path', '/tmp/tmpscw94lsq']
[2025-07-18T14:42:46.641+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask send_to_kafka
[2025-07-18T14:42:46.661+0000] {task_command.py:416} INFO - Running <TaskInstance: restaurant_pipeline.send_to_kafka manual__2025-07-18T14:42:45.033995+00:00 [running]> on host 221452b2e7e6
[2025-07-18T14:42:46.694+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='moran' AIRFLOW_CTX_DAG_ID='restaurant_pipeline' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T14:42:45.033995+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-18T14:42:45.033995+00:00'
[2025-07-18T14:42:46.694+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-18T14:42:46.695+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/streaming/producer.py']
[2025-07-18T14:42:46.699+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T14:42:46.748+0000] {subprocess.py:93} INFO - python: can't open file '/opt/streaming/producer.py': [Errno 2] No such file or directory
[2025-07-18T14:42:46.750+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-18T14:42:46.755+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-18T14:42:46.757+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=restaurant_pipeline, task_id=send_to_kafka, execution_date=20250718T144245, start_date=20250718T144246, end_date=20250718T144246
[2025-07-18T14:42:46.762+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task send_to_kafka (Bash command failed. The command returned a non-zero exit code 2.; 200)
[2025-07-18T14:42:46.780+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-18T14:42:46.805+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
