[2025-07-19T18:06:26.269+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_pipeline.stream_to_bronze scheduled__2025-07-19T18:04:00+00:00 [queued]>
[2025-07-19T18:06:26.273+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_pipeline.stream_to_bronze scheduled__2025-07-19T18:04:00+00:00 [queued]>
[2025-07-19T18:06:26.273+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-19T18:06:26.278+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): stream_to_bronze> on 2025-07-19 18:04:00+00:00
[2025-07-19T18:06:26.280+0000] {standard_task_runner.py:57} INFO - Started process 350 to run task
[2025-07-19T18:06:26.282+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'restaurant_pipeline', 'stream_to_bronze', 'scheduled__2025-07-19T18:04:00+00:00', '--job-id', '933', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_pipeline.py', '--cfg-path', '/tmp/tmpukjzaflg']
[2025-07-19T18:06:26.283+0000] {standard_task_runner.py:85} INFO - Job 933: Subtask stream_to_bronze
[2025-07-19T18:06:26.304+0000] {task_command.py:416} INFO - Running <TaskInstance: restaurant_pipeline.stream_to_bronze scheduled__2025-07-19T18:04:00+00:00 [running]> on host e3f5d8fc4eef
[2025-07-19T18:06:26.341+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your@email.com' AIRFLOW_CTX_DAG_OWNER='moran' AIRFLOW_CTX_DAG_ID='restaurant_pipeline' AIRFLOW_CTX_TASK_ID='stream_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T18:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T18:04:00+00:00'
[2025-07-19T18:06:26.342+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-19T18:06:26.342+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "docker exec -e AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-19T18:04:00+00:00' spark-iceberg spark-submit /home/iceberg/spark/stream_to_bronze.py"]
[2025-07-19T18:06:26.346+0000] {subprocess.py:86} INFO - Output:
[2025-07-19T18:06:27.610+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SparkContext: Running Spark version 3.5.6
[2025-07-19T18:06:27.610+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SparkContext: OS info Linux, 6.10.14-linuxkit, aarch64
[2025-07-19T18:06:27.611+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SparkContext: Java version 17.0.15
[2025-07-19T18:06:27.621+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO ResourceUtils: ==============================================================
[2025-07-19T18:06:27.622+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-07-19T18:06:27.622+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO ResourceUtils: ==============================================================
[2025-07-19T18:06:27.623+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SparkContext: Submitted application: StreamToBronze
[2025-07-19T18:06:27.631+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-07-19T18:06:27.635+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO ResourceProfile: Limiting resource is cpu
[2025-07-19T18:06:27.635+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-07-19T18:06:27.656+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SecurityManager: Changing view acls to: root,spark
[2025-07-19T18:06:27.657+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SecurityManager: Changing modify acls to: root,spark
[2025-07-19T18:06:27.657+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SecurityManager: Changing view acls groups to:
[2025-07-19T18:06:27.657+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SecurityManager: Changing modify acls groups to:
[2025-07-19T18:06:27.657+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: root, spark; groups with view permissions: EMPTY; users with modify permissions: root, spark; groups with modify permissions: EMPTY
[2025-07-19T18:06:27.682+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-07-19T18:06:27.806+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO Utils: Successfully started service 'sparkDriver' on port 41521.
[2025-07-19T18:06:27.818+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SparkEnv: Registering MapOutputTracker
[2025-07-19T18:06:27.834+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SparkEnv: Registering BlockManagerMaster
[2025-07-19T18:06:27.846+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-07-19T18:06:27.846+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-07-19T18:06:27.848+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-07-19T18:06:27.863+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0e419952-47a5-42b5-b39f-cbab6937a0ba
[2025-07-19T18:06:27.869+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-07-19T18:06:27.876+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-07-19T18:06:27.927+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-07-19T18:06:27.952+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-07-19T18:06:27.956+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2025-07-19T18:06:27.998+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO Executor: Starting executor ID driver on host 8b44f3d35cfa
[2025-07-19T18:06:27.998+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO Executor: OS info Linux, 6.10.14-linuxkit, aarch64
[2025-07-19T18:06:27.998+0000] {subprocess.py:93} INFO - 25/07/19 18:06:27 INFO Executor: Java version 17.0.15
[2025-07-19T18:06:28.000+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-07-19T18:06:28.001+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@5101bc9f for default.
[2025-07-19T18:06:28.009+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35375.
[2025-07-19T18:06:28.010+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO NettyBlockTransferService: Server created on 8b44f3d35cfa:35375
[2025-07-19T18:06:28.010+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-07-19T18:06:28.015+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 8b44f3d35cfa, 35375, None)
[2025-07-19T18:06:28.017+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO BlockManagerMasterEndpoint: Registering block manager 8b44f3d35cfa:35375 with 434.4 MiB RAM, BlockManagerId(driver, 8b44f3d35cfa, 35375, None)
[2025-07-19T18:06:28.018+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 8b44f3d35cfa, 35375, None)
[2025-07-19T18:06:28.020+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 8b44f3d35cfa, 35375, None)
[2025-07-19T18:06:28.218+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-07-19T18:06:28.222+0000] {subprocess.py:93} INFO - 25/07/19 18:06:28 INFO SharedState: Warehouse path is 'file:/app/spark-warehouse'.
[2025-07-19T18:06:29.214+0000] {subprocess.py:93} INFO - 25/07/19 18:06:29 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-07-19T18:06:29.223+0000] {subprocess.py:93} INFO - 25/07/19 18:06:29 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-07-19T18:06:29.223+0000] {subprocess.py:93} INFO - 25/07/19 18:06:29 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2025-07-19T18:06:29.897+0000] {subprocess.py:93} INFO - 25/07/19 18:06:29 INFO BaseMetastoreCatalog: Table loaded by catalog: my_catalog.bronze.Reservations_raw
[2025-07-19T18:06:29.909+0000] {subprocess.py:93} INFO - 25/07/19 18:06:29 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
[2025-07-19T18:06:29.939+0000] {subprocess.py:93} INFO - 25/07/19 18:06:29 INFO ResolveWriteToStream: Checkpoint root /tmp/checkpoints/reservations/scheduled__2025-07-19T18:04:00+00:00 resolved to file:/tmp/checkpoints/reservations/scheduled__2025-07-19T18:04:00+00:00.
[2025-07-19T18:06:29.939+0000] {subprocess.py:93} INFO - 25/07/19 18:06:29 WARN ResolveWriteToStream: spark.sql.adaptive.enabled is not supported in streaming DataFrames/Datasets and will be disabled.
[2025-07-19T18:06:29.971+0000] {subprocess.py:93} INFO - 25/07/19 18:06:29 INFO CheckpointFileManager: Writing atomically to file:/tmp/checkpoints/reservations/scheduled__2025-07-19T18:04:00+00:00/metadata using temp file file:/tmp/checkpoints/reservations/scheduled__2025-07-19T18:04:00+00:00/.metadata.c5f8a415-6883-45ae-abbc-6e1b889a94c2.tmp
[2025-07-19T18:06:30.004+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO CheckpointFileManager: Renamed temp file file:/tmp/checkpoints/reservations/scheduled__2025-07-19T18:04:00+00:00/.metadata.c5f8a415-6883-45ae-abbc-6e1b889a94c2.tmp to file:/tmp/checkpoints/reservations/scheduled__2025-07-19T18:04:00+00:00/metadata
[2025-07-19T18:06:30.019+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO MicroBatchExecution: Starting [id = d23178fd-5f5f-411e-b27f-3f217b22e112, runId = b34c74b2-2f60-4346-b12e-95662644fe90]. Use file:/tmp/checkpoints/reservations/scheduled__2025-07-19T18:04:00+00:00 to store the query checkpoint.
[2025-07-19T18:06:30.024+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO MicroBatchExecution: Reading table [org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaTable@465e9466] from DataSourceV2 named 'kafka' [org.apache.spark.sql.kafka010.KafkaSourceProvider@7ee91e76]
[2025-07-19T18:06:30.042+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO OffsetSeqLog: BatchIds found from listing:
[2025-07-19T18:06:30.042+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO OffsetSeqLog: BatchIds found from listing:
[2025-07-19T18:06:30.043+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO MicroBatchExecution: Starting new streaming query.
[2025-07-19T18:06:30.045+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO MicroBatchExecution: Stream started from {}
[2025-07-19T18:06:30.213+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-19T18:06:30.213+0000] {subprocess.py:93} INFO -   File "/home/iceberg/spark/stream_to_bronze.py", line 100, in <module>
[2025-07-19T18:06:30.213+0000] {subprocess.py:93} INFO -     read_kafka(
[2025-07-19T18:06:30.214+0000] {subprocess.py:93} INFO -   File "/home/iceberg/spark/stream_to_bronze.py", line 77, in read_kafka
[2025-07-19T18:06:30.214+0000] {subprocess.py:93} INFO -     df = df.withWatermark("checkin_timestamp", "48 hours")
[2025-07-19T18:06:30.215+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-19T18:06:30.215+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 1149, in withWatermark
[2025-07-19T18:06:30.215+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO AdminClientConfig: AdminClientConfig values:
[2025-07-19T18:06:30.215+0000] {subprocess.py:93} INFO - 	auto.include.jmx.reporter = true
[2025-07-19T18:06:30.215+0000] {subprocess.py:93} INFO - 	bootstrap.servers = [kafka:9092]
[2025-07-19T18:06:30.215+0000] {subprocess.py:93} INFO - 	client.dns.lookup = use_all_dns_ips
[2025-07-19T18:06:30.215+0000] {subprocess.py:93} INFO - 	client.id =
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	connections.max.idle.ms = 300000
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	default.api.timeout.ms = 60000
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	metadata.max.age.ms = 300000
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	metric.reporters = []
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	metrics.num.samples = 2
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	metrics.recording.level = INFO
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	metrics.sample.window.ms = 30000
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	receive.buffer.bytes = 65536
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	reconnect.backoff.max.ms = 1000
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	reconnect.backoff.ms = 50
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	request.timeout.ms = 30000
[2025-07-19T18:06:30.216+0000] {subprocess.py:93} INFO - 	retries = 2147483647
[2025-07-19T18:06:30.217+0000] {subprocess.py:93} INFO - 	retry.backoff.ms = 100
[2025-07-19T18:06:30.217+0000] {subprocess.py:93} INFO - 	sasl.client.callback.handler.class = null
[2025-07-19T18:06:30.217+0000] {subprocess.py:93} INFO - 	sasl.jaas.config = null
[2025-07-19T18:06:30.217+0000] {subprocess.py:93} INFO - 	sasl.kerberos.kinit.cmd = /usr/bin/kinit
[2025-07-19T18:06:30.217+0000] {subprocess.py:93} INFO - 	sasl.kerberos.min.time.before.relogin = 60000
[2025-07-19T18:06:30.218+0000] {subprocess.py:93} INFO - 	sasl.kerberos.service.name = null
[2025-07-19T18:06:30.218+0000] {subprocess.py:93} INFO - 	sasl.kerberos.ticket.renew.jitter = 0.05
[2025-07-19T18:06:30.218+0000] {subprocess.py:93} INFO - 	sasl.kerberos.ticket.renew.window.factor = 0.8
[2025-07-19T18:06:30.218+0000] {subprocess.py:93} INFO - 	sasl.login.callback.handler.class = null
[2025-07-19T18:06:30.218+0000] {subprocess.py:93} INFO - 	sasl.login.class = null
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.login.connect.timeout.ms = null
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.login.read.timeout.ms = null
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.login.refresh.buffer.seconds = 300
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.login.refresh.min.period.seconds = 60
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.login.refresh.window.factor = 0.8
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.login.refresh.window.jitter = 0.05
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.login.retry.backoff.max.ms = 10000
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.login.retry.backoff.ms = 100
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.mechanism = GSSAPI
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.clock.skew.seconds = 30
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.expected.audience = null
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.expected.issuer = null
[2025-07-19T18:06:30.219+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.jwks.endpoint.url = null
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.scope.claim.name = scope
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.sub.claim.name = sub
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.token.endpoint.url = null
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	security.protocol = PLAINTEXT
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	security.providers = null
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	send.buffer.bytes = 131072
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	socket.connection.setup.timeout.max.ms = 30000
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	socket.connection.setup.timeout.ms = 10000
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	ssl.cipher.suites = null
[2025-07-19T18:06:30.220+0000] {subprocess.py:93} INFO - 	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.endpoint.identification.algorithm = https
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.engine.factory.class = null
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.key.password = null
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.keymanager.algorithm = SunX509
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.keystore.certificate.chain = null
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.keystore.key = null
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.keystore.location = null
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.keystore.password = null
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.keystore.type = JKS
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.protocol = TLSv1.3
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.provider = null
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.secure.random.implementation = null
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.trustmanager.algorithm = PKIX
[2025-07-19T18:06:30.221+0000] {subprocess.py:93} INFO - 	ssl.truststore.certificates = null
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO - 	ssl.truststore.location = null
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO - 	ssl.truststore.password = null
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO - 	ssl.truststore.type = JKS
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO - 
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [EVENT_TIME_IS_NOT_ON_TIMESTAMP_TYPE] The event time `checkin_timestamp` has the invalid type "DOUBLE", but expected "TIMESTAMP".;
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO - EventTimeWatermark checkin_timestamp#103: double, 48 hours
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO - +- Project [checkin_id#83, customer_name#84, phone_number#85, branch_id#86, table_id#87, is_prebooked#88, checkin_date#89, checkin_time#90, guests_count#91, shift_manager#92, ((cast(cast(checkin_date#89 as string) as double) + cast(  as double)) + cast(checkin_time#90 as double)) AS checkin_timestamp#103]
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO -    +- Project [data#81.checkin_id AS checkin_id#83, data#81.customer_name AS customer_name#84, data#81.phone_number AS phone_number#85, data#81.branch_id AS branch_id#86, data#81.table_id AS table_id#87, data#81.is_prebooked AS is_prebooked#88, data#81.checkin_date AS checkin_date#89, data#81.checkin_time AS checkin_time#90, data#81.guests_count AS guests_count#91, data#81.shift_manager AS shift_manager#92]
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO -       +- Project [from_json(StructField(checkin_id,IntegerType,true), StructField(customer_name,StringType,true), StructField(phone_number,StringType,true), StructField(branch_id,IntegerType,true), StructField(table_id,IntegerType,true), StructField(is_prebooked,BooleanType,true), StructField(checkin_date,DateType,true), StructField(checkin_time,StringType,true), StructField(guests_count,IntegerType,true), StructField(shift_manager,StringType,true), json#79, Some(Etc/UTC)) AS data#81]
[2025-07-19T18:06:30.222+0000] {subprocess.py:93} INFO -          +- Project [cast(value#66 as string) AS json#79]
[2025-07-19T18:06:30.223+0000] {subprocess.py:93} INFO -             +- StreamingRelationV2 org.apache.spark.sql.kafka010.KafkaSourceProvider@55574c4, kafka, org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaTable@4a69cb98, [startingOffsets=earliest, kafka.bootstrap.servers=kafka:9092, subscribe=checkins], [key#65, value#66, topic#67, partition#68, offset#69L, timestamp#70, timestampType#71], StreamingRelation DataSource(org.apache.spark.sql.SparkSession@27e86c63,kafka,List(),None,List(),None,Map(kafka.bootstrap.servers -> kafka:9092, subscribe -> checkins, startingOffsets -> earliest),None), kafka, [key#58, value#59, topic#60, partition#61, offset#62L, timestamp#63, timestampType#64]
[2025-07-19T18:06:30.223+0000] {subprocess.py:93} INFO - 
[2025-07-19T18:06:30.247+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO SparkContext: Invoking stop() from shutdown hook
[2025-07-19T18:06:30.247+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-07-19T18:06:30.248+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-07-19T18:06:30.249+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO AppInfoParser: Kafka version: 3.5.1
[2025-07-19T18:06:30.250+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO AppInfoParser: Kafka commitId: 2c6fb6c54472e90a
[2025-07-19T18:06:30.250+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO AppInfoParser: Kafka startTimeMs: 1752948390247
[2025-07-19T18:06:30.253+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO SparkUI: Stopped Spark web UI at http://8b44f3d35cfa:4041
[2025-07-19T18:06:30.259+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-07-19T18:06:30.266+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO MemoryStore: MemoryStore cleared
[2025-07-19T18:06:30.266+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO BlockManager: BlockManager stopped
[2025-07-19T18:06:30.269+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-07-19T18:06:30.278+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-07-19T18:06:30.287+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO SparkContext: Successfully stopped SparkContext
[2025-07-19T18:06:30.288+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO ShutdownHookManager: Shutdown hook called
[2025-07-19T18:06:30.294+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-4a4915bd-edc8-4e21-a554-75fc2d034f6d/pyspark-ddd0b31a-0163-4973-9988-7417fe40971d
[2025-07-19T18:06:30.295+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-36e83b91-f921-4567-a438-71fcacaf13d8
[2025-07-19T18:06:30.295+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-4a4915bd-edc8-4e21-a554-75fc2d034f6d
[2025-07-19T18:06:30.302+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
[2025-07-19T18:06:30.303+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
[2025-07-19T18:06:30.303+0000] {subprocess.py:93} INFO - 25/07/19 18:06:30 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.
[2025-07-19T18:06:30.336+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-19T18:06:30.343+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-19T18:06:30.345+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=restaurant_pipeline, task_id=stream_to_bronze, execution_date=20250719T180400, start_date=20250719T180626, end_date=20250719T180630
[2025-07-19T18:06:30.358+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-19T18:06:30.359+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-19T18:06:30.359+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-19T18:06:30.363+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-19T18:06:30.363+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-19T18:06:30.363+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['your@email.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-19T18:06:30.372+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 933 for task stream_to_bronze (Bash command failed. The command returned a non-zero exit code 1.; 350)
[2025-07-19T18:06:30.408+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-19T18:06:30.435+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
